### PR TITLE
Add Region Labels

### PR DESCRIPTION
**Pull request by mistic100**
This is the same thing as #1586 with following changes :
- code in the right files
- update unit test
- update example
- split "padding" in "paddingX" and "paddingY"
- fix text opacity
- fix transition

### CODE REVIEW

**Comment by monstasat** [comment]
when this will be merged into master?

**Comment by dunderpate** [comment]
Can someone provide an update on this? It'd be a really nice feature and someone's already done the work even though it may need to be re-based. Any ETA on this being merged, or any other efforts to introduce region labels?

**Comment by panthony** [comment]
@dunderpate Unlikely I'll have time for this as I'm not using this feature at all, do not hesitate to chip in and rebase it!

**Comment by dunderpate** [comment]
Hi @panthony, thanks for the response. I totally understand and would be happy to take a crack at re-basing the patch.

**Comment by panthony** [comment]
Closing in favor of #2703

**Pull request closed without merging**
