### PR TITLE
Add mouse move events.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith gordon.smith@lexisnexis.com

### CODE REVIEW

**Comment by aendrew** [comment]
Hi @GordonSmith!

First off, apologies for the delay in getting back to you on this.

Secondly, nice PR, I can understand the need for mousemove events. Because this is a new feature, could you please write a unit test for this?

Thanks!

**Comment by GordonSmith** [comment]
@aendrew - where are the unit tests?  Also do you have a mechanism for testing mouse events already?

**Comment by kenbier** [comment]
@GordonSmith tests are in /spec. Here is an [example](https://github.com/c3js/c3/blob/223404a79246c61d150d8a209dbdc81f6955083b/spec/tooltip-spec.js#L55).

**Comment by aendrew** [comment]
This doesn't seem very useful for most users and is outdated. Closing; please add a valid use-case or demonstrate appetite for this feature and I'll consider reopening.

**Pull request closed without merging**
