### PR TITLE
issue 1662

### PR DESCRIPTION
**Pull request by greenafrican**
#1662

### CODE REVIEW

**Comment by aendrew** [comment]
@greenafrican This looks good, but could you please add a unit test demonstrating the behaviour you've fixed? Thank you!

**Comment by greenafrican** [comment]
@aendrew Thanks. I've included 2 tests in `spec/data-spec.js` and have tested them locally and they pass fine. I'm not sure how to pass the Travis CI build though as it says not to include the build output files for PRs and I'm guessing Travis is using the old `c3.js` file?

**Comment by aendrew** [comment]
@greenafrican Thanks for adding tests! 

Right you are, for some reason there's no build step on Travis that re-concatenates everything, meaning PRs won't ever pass (I've fixed this via #1679). I've run your tests locally and they pass, am marking RTBC. 😄

**Comment by mgdesign** [comment]
Any chance this PR could advance in any way? The #1355 PR seems a great advancement! :)

**Comment by aendrew** [comment]
Apologies for the delay, have merged this.

**Comment by kt3k** [comment]
Published at v0.4.13.

**Pull request merged**
