### PR TITLE
Fixes unexpected category behavior when multiple series are used. Fix…

### PR DESCRIPTION
**Pull request by rlindner81**
…es #1643

### CODE REVIEW

**Comment by meum** [comment]
Can this be merged, please?

**Comment by kt3k** [comment]
I confirmed that this fixes the example in #1643. Thanks for the contribution!

**Comment by kt3k** [comment]
Will release as v0.4.14 in a few days.

**Comment by kt3k** [comment]
Published as [v0.4.14](https://github.com/c3js/c3/releases/tag/v0.4.14). Thanks!

**Pull request merged**
