### PR TITLE
Version 1.0 [work-in-progress]

### PR DESCRIPTION
**Pull request by aendrew**
This PR is meant to rally efforts towards getting to v1 of C3.js.

Key features of v1:
- [ ] D3 v4 compat (#1648)
- [ ] Charts provided via plugin system
- [ ] Component parts separated into ES2015 modules
- [ ] Each part of internal API fully documented
- [ ] TypeScript definition generated from documentation

### CODE REVIEW

**Comment by panthony** [comment]
Hi @aendrew,

Is this project still being worked on ? 

I really like this library I'm using it a lot and I'd rather invest time fixing and adding missing things that redoing everything using another chart library.

But looking at the issues that are never closed or responded to, PR that are never merged, and this big bang PR that will break every other ones I wonder if it is still worth it to try to fix things.

Maybe I could help in some way ?

**Comment by aendrew** [comment]
@panthony I'm honestly not sure what the best approach is at this point. I've admittedly halted work on this PR for the moment as I'm drowning in work and behind deadline on my book, but am hoping to return to it at the start of next year with fresh eyes. I think what's needed more than anything is a feature freeze until we can get everything sorted out architecturally, so if you're wanting features C3 lacks, you may want to look elsewhere for the moment, unfortunately.

**Comment by panthony** [comment]
@aendrew Well I could always workaround the issues, fix them in a fork, or directly implement what I need using D3 directly.

What worries me is more the issues not being closed, PR proposing unit tested fix not being merged, etc.

I'd like to avoid diverging too much from the official repository.

And are you alone on c3 ?

When I walk around issues because I'm looking for something I often see duplicate issues, or simply questions about "how do things" that could be closed since they should use the google groups instead.

And I honestly think that the scope of this PR is way to broad and should be broken down into several steps in order to not freeze everything for months. Isn't it possible to move code as module little by little ?

**Comment by aendrew** [comment]
@panthony Good points. I've not gotten a lot of input or buy-in from the other contributors so I don't perceive there to be a lot of appetite for my current tack with this. My feeling is that it might be better to close this PR for now to prevent confusion, re-evaluating efforts to get to v1.0 in the New Year.

**Pull request closed without merging**
