### PR TITLE
Added support to zoom types (scroll and drag) with option to disable default zoom behavior

### PR DESCRIPTION
**Pull request by mistic**
New api for zoom:

``` javascript
zoom: {
    enabled: true,
    type: 'drag', // can be [drag, scroll]
    disableDefaultBehavior: false // if yes chart don't zoom but user will have x domain of the zoom box. This is more util for drag zoom type.
}
```

### CODE REVIEW

**Comment by aendrew** [comment]
Hi @misticini! 

Looks good to me! :+1: Thank you for adding documentation, that's always massively appreciated! :100: 

I just tested it and it behaves wonderfully. Very nicely done! 

Please do the following —

1. Remove all the compiled assets — c3.js, c3.min.js, c3.css — from your commits. These get created during releases only. 
1. Squash all your commits.

Thanks!

**Comment by misticini** [comment]
Hi @aendrew 

1. Done
2. Done

Thank u for your feedback :+1:

**Comment by aendrew** [comment]
@misticini Brilliantly done! RTBC, merge away @masayuki0812! :smile: :shipit: :100: :boom:

**Comment by aendrew** [comment]
@misticini Quick question — any idea why the commit's author is @tiagoferreira-mindera? Is that just a new account or what?

**Comment by misticini** [comment]
Hi @aendrew 

The commit's author is only my company's github account :)

**Comment by misticini** [comment]
I've changed the commits author :)

**Comment by Irrelon** [comment]
Is there an intention to merge this in at some point?

**Comment by mistic** [comment]
@Irrelon I don't really know because it's already pass more than an year :( 

Hey guys what do u think? ( @aendrew @masayuki0812  ) ?

**Comment by a244096658** [comment]
Hi,

When will this new feature be added into a new release? Thanks!

**Comment by binakot** [comment]
Please, add this PR to the next release :shipit:

**Comment by tovinayv** [comment]
Even i'm looking for this feature..

**Comment by tovinayv** [comment]
Is there any ETA for this?

**Comment by mistic** [comment]
( @aendrew @masayuki0812 @kt3k ) any plans to ever release this? It looks like it's a very requested feature 😃

**Comment by mageshveeraa** [comment]
@aendrew @masayuki0812 @kt3k @mistic  When will this be released? I wanted this feature.

**Comment by kt3k** [comment]
I created another PR to fit this change to the current code base. https://github.com/c3js/c3/pull/2439

Could anyone check the behavior on [a sample page](https://468-11496279-gh.circle-artifacts.com/0/htdocs/samples/zoom_type.html)?

**Comment by kt3k** [comment]
The change is merged as #2439.

**Pull request closed without merging**
