### PR TITLE
make the target completely hidden

### PR DESCRIPTION
**Pull request by Xuefeng-Zhu**
Fix https://github.com/c3js/c3/issues/1790

### CODE REVIEW

**Comment by panthony** [comment]
Hi,

Do you think you could add some asserts for this in 'api.show-spec'?

Thanks!

**Comment by Xuefeng-Zhu** [comment]
@panthony Sorry, we may not have time to do it at this point

**Comment by panthony** [comment]
@Xuefeng-Zhu No worries, hard to ask for tests so long after :)

**Comment by panthony** [comment]
Tested and it does fix the issue.

**Pull request merged**
