### PR TITLE
Added "bar.space" parameter to set space between bars in bar charts.

### PR DESCRIPTION
**Pull request by Kreozot**
(Issue #1327)

### CODE REVIEW

**Comment by Kreozot** [comment]
The parameter is multiplier for bar width. So it should be from 0 to 0.5.

**Comment by aendrew** [comment]
@kreozot This is a terrific feature and I really want to add it, would help some layout problems with bar charts. :+1:

Could you please add a unit test or two demonstrating this feature works? At this point, we're requiring unit tests for any new features on the 0.4.x branch — if you need help with that, drop me a line on [Gitter](http://gitter.im/c3js/c3) and I'll walk you through it. Thanks!

**Comment by panthony** [comment]
I am too interested by this feature so I tried to write some basic tests but it appears to have an unexpected behavior in my opinion.

I tried with something like this:

```javascript
            return {
                size: {
                  width: 500
                },
                data: {
                    columns: [
                        ['data1', 30, 200, 100],
                        ['data2', 50, 20, 10],
                        ['data3', 150, 120, 110]
                    ],
                    type: 'bar'
                },
                bar: {
                    space: 0.5
                }
            }
```

I was expecting the bar's width to shrink to make room for the added space but this is not the case. The bar's width stays the same and the container `.c3-chart-bars` growth.

I have the feeling that this will bring issues at some point.

**Comment by jashetty** [comment]
Great feature! Any updates on when this is going to be merged??

**Comment by kt3k** [comment]
closed in favor of #2146.

**Pull request closed without merging**
