### PR TITLE
Building with rollup

### PR DESCRIPTION
**Pull request by amenadiel**
In this PR the following changes were made:
- Updates dependencies (mostly grunt and its tasks + phantom-prebuilt)
- Rearranges the structure of `/src` folder to reflect the module structure (Chart, Axis, ChartInternal)
  - No file should contain both Chart.prototype and ChartInternal.prototype declarations. In that case, said file was split in two.
  - `src/core.js` was removed. Different parts of its code went to `src/chart/index.js`, `src/axis/index.js`, `src/chartinternal/index.js`, `src/chart/head.js` and `src/chart/tail.js` 
- Modifies the `grunt concat:dist` task structure to reflect said rearrangement
- Three additional `concat` tasks were added to generate `es6_module/axis.js`, `es6_module/chart.js` and `es6_module/chartinternal.js`
- Adds as `grunt-rollup` task and its entry point `es6_modules/rollup.entry.js`. 
- Running `grunt build_rollup` will recreate each module in `es6_modules` and use rollup to create `c3.es6.js` file in the root folder.

After running `grunt build` (with the new `src` structure), running `npm test` yielt the same 5 failures that are already happening. in dev :+1:  

After running `grunt build_rollup`, and modifying `karma.conf.js` to load `c3.es6.js` instead of `c3.js`, the result is the same. :tada:  (still short of 5 tests)

### CODE REVIEW

**Comment by amenadiel** [comment]
Ref: #1648

**Comment by aendrew** [comment]
This is some terrific work; will try to get around to reviewing it sometime this week! :+1:

**Comment by aendrew** [comment]
@amenadiel Apologies for the lack of progress on reviewing this PR thus far; it's a big one and I think it does quite a lot well. Am questioning whether chartInternal.js should be split up a bit, but I ultimately like the approach you've taken. 

Even if this isn't merged immediately, I think that I might take it and use it as the basis for v1.0.0, which I and a few others are starting to begin considering. Hang tight!

**Comment by aendrew** [comment]
I've rebased against `master` and pushed to `v1-dev`. I'm going to do a thorough code clean-up and work off that branch for experimentation purposes for the next bit.

**Comment by kt3k** [comment]
Closing in favor of #2037. Thanks for the constribution anyway.

**Pull request closed without merging**
