### PR TITLE
Introduce tooltip.position callback function

### PR DESCRIPTION
**Pull request by ku**
Added a callback function to control the position of the tooltip programmatically to tooltip configuration.
`circle` element is given if `grouped` option is false and `region` element is given if it's true.

This callback function allows to show tooltip on the top of the data points like this.

with following configuration.

```
        tooltip: {
          grouped: false,
          position: function (data, width, height, element) {
            var chartOffsetX = document.querySelector("#chart").getBoundingClientRect().left;
            var graphOffsetX = document.querySelector("#chart g.c3-axis-y").getBoundingClientRect().right;
            var tooltipWidth = document.getElementById('tooltip').parentNode.clientWidth;
            var x = (parseInt(element.getAttribute('cx')) ) + graphOffsetX - chartOffsetX - Math.floor(tooltipWidth/2);
            var y = element.getAttribute('cy');
            var y = y - height - 14;
            return {top: y, left: x}
          },
          contents: function (d, defaultTitleFormat, defaultValueFormat, color) {
            d = Math.floor(d[0].value)
            return '<div id="tooltip" class="module-triangle-bottom">' + d + ' wows</div>'
          }
        }
```

### CODE REVIEW

**Comment by aendrew** [comment]
Oh rad! Good to know it can do this now. The documentation definitely needs to be updated to include this!

**Comment by parisnakitakejser** [comment]
Thanks a lot, you save my night! :+1:

**Comment by stuartm** [comment]
Is it possible to modify top while leaving left unchanged, or vice-versa, or is it always necessary to recalculate both?

**Comment by vinikento** [comment]
There's just one problem:
When values match on the graphic, it only show one data.

**Comment by PeddiMahesh** [comment]
If we are using xs in data how to get 'cx' and 'cy' values of point.

**Comment by opensrcken** [comment]
This does not work for bar charts.

**Comment by jayantsr83** [comment]
How this code will work with donut chart? Any Help?

**Comment by JRPendarvis** [comment]
Can the function be an external file?

**Pull request merged**
