### PR TITLE
Fixes Cannot read property 'keys' of null

### PR DESCRIPTION
**Pull request by pajcho**
When chart is destroyed while transitions are in progress we are getting Cannot read property 'keys' of null like many people reported as a part of #1205 

This solves issue in a same way like #1205 and #1305 are solved here https://github.com/FernCreek/c3/commit/a26b38165f4c0b97bb2f365978f3df9e12446530

### CODE REVIEW

**Comment by ilacyero** [comment]
I think that will be better if you use:
```
    if (!config || !$$.d3) {
        return null;
    }
```
The change is really small and you will fix it too.

**Comment by mervinva** [comment]
+1

**Comment by panthony** [comment]
Hi,

Please modify the proper source file in `src` directory and do not commit the `c3.js` file which is overwritten by the build phase.

Also, Do what @ilacyero suggested and do an early return if config is not available anymore.

This is the same thing except it's more readable and introduce less changes.

Thanks

**Comment by panthony** [comment]
No response & `Object.keys` is used instead of `$$.d3.keys`, closing

**Pull request closed without merging**
