### PR TITLE
Ie9 csv fix

### PR DESCRIPTION
**Pull request by jfrazier**
Fix error parsing csv from xhr request callback object

### CODE REVIEW

**Comment by aendrew** [comment]
Hi @jfrazier! Apologies for the incredibly long delay in getting to this PR!

1. Please remove c3.js and c3.css (the built files) from your commits, these get built on releases.
2. Squash your commits, and rebase them against `master`. 

Thank you!

**Comment by kt3k** [comment]
Going to merge with appending comments. ( Approved by @masayuki0812 .

**Comment by aendrew** [comment]
Merged in 6f3deac.

**Comment by kt3k** [comment]
Published at v0.4.13.

**Pull request closed without merging**
