### PR TITLE
Fix for Chrome 48 removal of SVGPathSeg and SVGPathSegList APIs

### PR DESCRIPTION
**Pull request by adufilie**
https://www.chromestatus.com/feature/5708851034718208

### CODE REVIEW

**Comment by adufilie** [comment]
updated patch to add jshint ignore comments around polyfill.js

**Comment by ekeyte** [comment]
WOW thanks for doing this!!!

**Comment by aendrew** [comment]
Hi, apologies for the delay in getting to this.

I'm conditionally merging this because it fixes a very real immediate need, but I don't think polyfilling SVGPathSeg is the best route long-term — we really need to remove SVGPathSeg altogether at some point.

**Comment by aendrew** [comment]
Hello all,

I've created a new branch called [`dev`](https://github.com/masayuki0812/c3/tree/dev) that I'm using to merge in all new changes. This PR has been merged into that and will be closed once dev is merged into master. Thanks for your contribution @adufilie!

**Pull request merged**
