### PR TITLE
Fix for issue http://github.com/c3js/c3/issues/1691

### PR DESCRIPTION
**Pull request by kelthuzad**
This is the bugfix for Fix for issue #1691 
The bug was introduced with the implementation of #1471

See http://jsfiddle.net/L3obmfsn/ for a working example.

If an object has key that contains . or [], it is now correctly found
instead of searching for an inner object or array that does not exist.
Example:
var data = [{"key.withdot":"1"}]; // did not work before, works now
var data2 = [{"key":{"innerkey":"1"}}]; // still works

Updated test with new bugfix.

### CODE REVIEW

**Comment by tsileo** [comment]
Any update on this issue?

**Comment by DoomyTheFroomy** [comment]
After I have run into the same problem again, could you please let this pass and release a new version? This would be a great new years present 👍 🥇

**Comment by carmamir** [comment]
Would be great to include this bug fix into a main release as it is a big issue with any titles having dots (starting with domain names !!!)

**Comment by scherrs** [comment]
Is there an update on this issue?

**Comment by 1Jesper1** [comment]
Can we merge this pr?

**Comment by svki0001** [comment]
Anything new to merging this?

**Comment by miladtai** [comment]
When will this problem be solved ?

**Comment by kt3k** [comment]
closing in favor of https://github.com/c3js/c3/pull/2761

**Pull request closed without merging**
